sudo: required

services:
  - docker

env:
  global:
    - GIT_LFS_VERSION=2.5.1

matrix:
  include:
    - os: linux
      language: c
      env:
        - TARGET_PLATFORM=ubuntu
        - GIT_LFS_CHECKSUM=9565fa9c2442c3982567a3498c9352cda88e0f6a982648054de0440e273749e7
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev

    - os: osx
      language: c
      env:
        - TARGET_PLATFORM=macOS
        - GIT_LFS_CHECKSUM=2ade1f42d51b012db0658838d6e1050af7e269d46c84d978bca82d74788e1c2e

    - os: linux
      language: c
      env:
        - TARGET_PLATFORM=win32
        - WIN_ARCH=64
        - GIT_FOR_WINDOWS_URL=https://github.com/git-for-windows/git/releases/download/v2.19.0.windows.1/MinGit-2.19.0-64-bit.zip
        - GIT_FOR_WINDOWS_CHECKSUM=424d24b5fc185a9c5488d7872262464f2facab4f1d4693ea8008196f14a3c19b
        - GIT_LFS_CHECKSUM=62ce983c2e4074b58bc88f20c12e15f00d2fb27acaf7219c860f1fd21af0f991

    - os: linux
      language: c
      env:
        - TARGET_PLATFORM=win32
        - WIN_ARCH=32
        - GIT_FOR_WINDOWS_URL=https://github.com/git-for-windows/git/releases/download/v2.19.0.windows.1/MinGit-2.19.0-32-bit.zip
        - GIT_FOR_WINDOWS_CHECKSUM=83cf018bd6f5c24e2b3088539bbeef9067fd632087d094d447a3a0ff676e7bd7
        - GIT_LFS_CHECKSUM=64eb8782df371e5ef3b8cf07134a745be2b782920726ba2b924cc3d56b7c03ed

    - os: linux
      language: go
      env:
        - TARGET_PLATFORM=arm64

compiler:
  - gcc

script:
  - script/build.sh && script/package.sh

branches:
  only:
    - master
    - /^v[0-9]*.[0-9]*.[0.9]*.*$/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - ${TRAVIS_BUILD_DIR}/output/dugite-native-v*.tar.gz
    - ${TRAVIS_BUILD_DIR}/output/dugite-native-v*.lzma
  skip_cleanup: true
  draft: true
  tag_name: $TRAVIS_TAG
  on:
    tags: true
