matrix:
  include:
    - os: linux
      language: c
      env:
        - PLATFORM=ubuntu
        - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v1.5.5/git-lfs-linux-amd64-1.5.5.tar.gz
        - GIT_LFS_CHECKSUM=910b2b5c158b238256087cae9b84cbc0bfb83c061d5b41161b79ca08cf61b2e8

    - os: osx
      language: c
      env:
       - PLATFORM=macOS
       - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v1.5.5/git-lfs-darwin-amd64-1.5.5.tar.gz
       - GIT_LFS_CHECKSUM=2227668c76a07931dd387602f67c99d5d42f0a99c73b76f8949bbfe3a4cc49c7
    # let's do the packaging here for Windows
    - os: linux
      language: c
      env:
       - PLATFORM=win32
       - GIT_FOR_WINDOWS_URL=https://github.com/git-for-windows/git/releases/download/v2.11.1.windows.1/MinGit-2.11.1-64-bit.zip
       - GIT_FOR_WINDOWS_CHECKSUM=668d16a799dd721ed126cc91bed49eb2c072ba1b25b50048280a4e2c5ed56e59
       - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v1.5.5/git-lfs-windows-amd64-1.5.5.zip
       - GIT_LFS_CHECKSUM=7c23635f34b0b4eed55621231148ef3e0de9a46e2d629b4bba7f706a96ae77ea

compiler:
  - gcc

script:
  - script/build.sh
  - script/package.sh
