matrix:
  include:
    - os: linux
      language: c
      env:
        - TARGET_PLATFORM=ubuntu
        - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v2.1.0/git-lfs-linux-amd64-2.1.0.tar.gz
        - GIT_LFS_CHECKSUM=0260d1908b097dcd703ef6cf83d9c32c1a418325d29b063bf03a165e3dd8e364

    - os: osx
      language: c
      env:
       - TARGET_PLATFORM=macOS
       - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v2.1.0/git-lfs-darwin-amd64-2.1.0.tar.gz
       - GIT_LFS_CHECKSUM=e7c841a4a7d6e5f319c21f7836f6cbad1f1abe93c3dc6f532903c9b8cf589b3c

    - os: linux
      language: c
      env:
       - TARGET_PLATFORM=win32
       - GIT_FOR_WINDOWS_URL=https://github.com/git-for-windows/git/releases/download/v2.13.0.windows.1/MinGit-2.13.0-64-bit.zip
       - GIT_FOR_WINDOWS_CHECKSUM=20acda973eca1df056ad08bec6e05c3136f40a1b90e2a290260dfc36e9c2c800
       - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v2.1.0/git-lfs-windows-amd64-2.1.0.zip
       - GIT_LFS_CHECKSUM=a40adc489a99d1b7809aab89fa78b6dee2399af6542e4b9faae552a7a248c1ce

compiler:
  - gcc

script:
  - script/build.sh
  - script/package.sh

branches:
  only:
  - master
  - /^v[0-9]*.[0-9]*.[0.9]*.*$/

deploy:
  provider: releases
  api_key:
    secure: PZYs7hghA8bk+a9B9dsT4TcbmrGgPjVSKIXG+FGEX4ndd7thvYIuVNvGwY2qzw3QNPIaS8bsaR4u0OzO5PQ04maRcYBvkk3xWhB1VxMreokrz1lD0ee5UBzZcuKMuXpBatMJHQfbzRpJxD6c9ipP56lNeTB+ZZnKoGeTUO6BA2neDSHmTwU5Ps3aDRQ8VjK9/A6TzSQqczKBmM7t4g2RdC2+b0qH+2Waw2Rdsvf34SQiIixomXXE3sJaxGSXGtFg1+IOSnirJ/qT8sTcTwVRfCLzuQdbVfNbWPPRkBpKNOMxY8qJeEEa3TNu2yKstWva+JDLuDwQ/D5Lxl1YN7yFBSdiTODbfLRaunvbphrLMiho3QGcSYTqclNxrcjB5cuqq58jC6PR5bK/LGQd6jgUhRkuJOhcxpj5eL9hmho8Yr66laROYxCnPlCENfqlXxcpCuqwMDvwxoD8U9u6hViDU2FtMS/9QwNrgkKBOCiOmiWm29NZR1S9o68DZ3trNn63F/IVaZpkfQhLg+waLKoqL54xtOmhQwEzUyyTWF3jcuLLluCpWAj6Vcttj9zLFQ0sdUWEJiuqhpmOZcgicoFd+j5eNZz7Q9l3UoyAtOowuNLHCqK0IO1Cb9Ib6+L7PscUKAlgLVMDSHe1RxuJ4EhwraqTUrXUs+aq57qyEBn9AV8=
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/dugite-native-v*.tar.gz
  skip_cleanup: true
  on:
    tags: true
