matrix:
  include:
    - os: linux
      language: c
      env:
        - TARGET_PLATFORM=ubuntu
        - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v2.3.4/git-lfs-linux-amd64-2.3.4.tar.gz
        - GIT_LFS_CHECKSUM=6755e109a85ffd9a03aacc629ea4ab1cbb8e7d83e41bd1880bf44b41927f4cfe

    - os: osx
      language: c
      env:
       - TARGET_PLATFORM=macOS
       - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v2.3.4/git-lfs-darwin-amd64-2.3.4.tar.gz
       - GIT_LFS_CHECKSUM=b16d4b7469b1fa34e0e27bedb1b77cc425b8d7903264854e5f18b0bc73576edb

    - os: linux
      language: c
      env:
       - TARGET_PLATFORM=win32
       - GIT_FOR_WINDOWS_URL=https://github.com/git-for-windows/git/releases/download/v2.15.1.windows.1/MinGit-2.15.1-64-bit.zip
       - GIT_FOR_WINDOWS_CHECKSUM=5e38d13241b0742e6673bc5116ac82e851dd1fad01c660c943017f4549b6afea
       - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v2.3.4/git-lfs-windows-amd64-2.3.4.zip
       - GIT_LFS_CHECKSUM=18c47fd2806659e81a40fbd6f6b0598ea1802635ce04fb2317d75973450a3fe5

compiler:
  - gcc

script:
  - script/build.sh
  - script/package.sh

branches:
  only:
  - master
  - /^v[0-9]*.[0-9]*.[0.9]*.*$/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/dugite-native-v*.tar.gz
  skip_cleanup: true
  on:
    tags: true
