matrix:
  include:
    - os: linux
      language: c
      env:
        - TARGET_PLATFORM=ubuntu
        - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v2.3.0/git-lfs-linux-amd64-2.3.0.tar.gz
        - GIT_LFS_CHECKSUM=5913ed4d023efe30a3f8f536db7cd97c7b76ba68b189baef8428b1d71d82f2f4

    - os: osx
      language: c
      env:
       - TARGET_PLATFORM=macOS
       - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v2.3.0/git-lfs-darwin-amd64-2.3.0.tar.gz
       - GIT_LFS_CHECKSUM=37d588897194fe959d8d39bae1f057d486be53e0f2f7252abeacfd8aa31da9ee

    - os: linux
      language: c
      env:
       - TARGET_PLATFORM=win32
       - GIT_FOR_WINDOWS_URL=https://github.com/git-for-windows/git/releases/download/v2.14.1.windows.1/MinGit-2.14.1-64-bit.zip
       - GIT_FOR_WINDOWS_CHECKSUM=65c12e4959b8874187b68ec37e532fe7fc526e10f6f0f29e699fa1d2449e7d92
       - GIT_LFS_URL=https://github.com/git-lfs/git-lfs/releases/download/v2.3.0/git-lfs-windows-amd64-2.3.0.zip
       - GIT_LFS_CHECKSUM=0be7e8755e1c2d9a598f369ce1db63fd7f2a8985d1c078cb815a3e50961066c2

compiler:
  - gcc

script:
  - script/build.sh
  - script/package.sh

branches:
  only:
  - master
  - /^v[0-9]*.[0-9]*.[0.9]*.*$/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/dugite-native-v*.tar.gz
  skip_cleanup: true
  on:
    tags: true
