sudo: required

services:
  - docker

env:
  global:
    - GIT_LFS_VERSION=2.5.0

matrix:
  include:
    - os: linux
      language: c
      env:
        - TARGET_PLATFORM=ubuntu
        - GIT_LFS_CHECKSUM=d840829bca0827fb14537fbcd6fdba192dd74a67d0d5a6fb12d060c14a876ba7
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev

    - os: osx
      language: c
      env:
       - TARGET_PLATFORM=macOS
       - GIT_LFS_CHECKSUM=41c607f2a73eec2cc28464d6c867819139ced137a8fa9bdc13c3bf3b98d6bfb2

    - os: linux
      language: c
      env:
       - TARGET_PLATFORM=win32
       - WIN_ARCH=64
       - GIT_FOR_WINDOWS_URL=https://github.com/git-for-windows/git/releases/download/v2.18.0.windows.1/MinGit-2.18.0-64-bit.zip
       - GIT_FOR_WINDOWS_CHECKSUM=1dfd05de1320d57f448ed08a07c0b9de2de8976c83840f553440689b5db6a1cf
       - GIT_LFS_CHECKSUM=452375d3968491520df29cde989164c41c1c4ff12ba30dfb343872f6d24016f1

    - os: linux
      language: c
      env:
       - TARGET_PLATFORM=win32
       - WIN_ARCH=32
       - GIT_FOR_WINDOWS_URL=https://github.com/git-for-windows/git/releases/download/v2.18.0.windows.1/MinGit-2.18.0-32-bit.zip
       - GIT_FOR_WINDOWS_CHECKSUM=c2f59c121d0f5aac31c959e5ba2878542b6cbca6604778566061d45585e70895
       - GIT_LFS_CHECKSUM=408f95d919037b068318cb2affb450c17a46915fe6b3d9b10dfc15dc0df15bca

    - os: linux
      language: go
      env:
       - TARGET_PLATFORM=arm64

compiler:
  - gcc

script:
  - script/build.sh && script/package.sh

branches:
  only:
  - master
  - /^v[0-9]*.[0-9]*.[0.9]*.*$/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - ${TRAVIS_BUILD_DIR}/output/dugite-native-v*.tar.gz
    - ${TRAVIS_BUILD_DIR}/output/dugite-native-v*.lzma
  skip_cleanup: true
  draft: true
  tag_name: $TRAVIS_TAG
  on:
    tags: true
