image: Visual Studio 2015

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:
  TARGET_PLATFORM: win32
  GIT_FOR_WINDOWS_URL: https://github.com/git-for-windows/git/releases/download/v2.18.0.windows.1/MinGit-2.18.0-64-bit.zip
  GIT_FOR_WINDOWS_CHECKSUM: 1dfd05de1320d57f448ed08a07c0b9de2de8976c83840f553440689b5db6a1cf
  GIT_LFS_URL: https://github.com/git-lfs/git-lfs/releases/download/v2.4.2/git-lfs-windows-amd64-2.4.2.zip
  GIT_LFS_CHECKSUM: 4c95d8e842ef55013c8ac99c4ffcad2a20a41bc41bd8e0943a228a03e07cd976

build_script:
  - cmd: git submodule update --init --recursive
  - bash script\build.sh
  - bash script\package.sh

test: off
