image: Visual Studio 2015

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:
  TARGET_PLATFORM: win32
  GIT_FOR_WINDOWS_URL: https://github.com/git-for-windows/git/releases/download/v2.16.0-rc0.windows.1/MinGit-2.16.0.rc0.windows.1-64-bit.zip
  GIT_FOR_WINDOWS_CHECKSUM: 68e12e8c37143633e2d6b4d31eacc03abe30e4963414506ff97f3fb865def073
  GIT_LFS_URL: https://github.com/git-lfs/git-lfs/releases/download/v2.3.4/git-lfs-windows-amd64-2.3.4.zip
  GIT_LFS_CHECKSUM: 18c47fd2806659e81a40fbd6f6b0598ea1802635ce04fb2317d75973450a3fe5

build_script:
  - cmd: git submodule update --init --recursive
  - bash script\build.sh
  - bash script\package.sh

test: off
